apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "concert.fullname" . }}-config
  labels:
    {{- include "concert.labels" . | nindent 4 }}
data:
  DB_Name: {{ .Values.config.dbName | quote }}
  DB_Host: {{ include "concert.dbHost" . | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_User: {{ .Values.config.dbUser | quote }}
  DB_SSLMode: {{ .Values.config.dbSSLMode | quote }}
  PORT: {{ .Values.config.port | quote }}
  APP_URL: {{ .Values.config.appURL | quote }}
  TEMPORAL_HOST: {{ .Values.config.temporalHost | quote }}
