apiVersion: v1
kind: Secret
metadata:
  name: {{ include "concert.fullname" . }}-secret
  labels:
    {{- include "concert.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_Password: {{ include "concert.dbPassword" . | quote }}
{{- if .Values.secrets.resendApiKey }}
  RESEND_API: {{ .Values.secrets.resendApiKey | quote }}
{{- end }}
