apiVersion: v1
kind: Service
metadata:
  name: {{ include "concert.fullname" . }}-server
  labels:
    {{- include "concert.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "concert.selectorLabels" . | nindent 4 }}
    component: server
